# Generated by Django 4.2 on 2024-02-15 21:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_reserver_email_alter_reserver_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserver',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
